version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: zenadmin
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
volumes:
  postgres:
